apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: go-controller-sa-rb
  namespace: k8s-go-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: go-controller-sa-role
subjects:
- kind: ServiceAccount
  name: go-controller-sa
  namespace: k8s-go-controller
