apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: go-controller-sa-role
  namespace: k8s-go-controller
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - namespaces
  verbs:
  - list
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - list
  - get
